// GFXTAB AI Studio — Product Definitions
// All 20 mockup products with metadata and template info

export const PRODUCTS = [
  {
    id: 'tshirt-crew',
    name: 'Vintage Leather Journal Branding',
    category: 'stationery',
    icon: '📓',
    description: 'Classic leather bound notebook journal mockup template',
    printZone: { x: 0.25, y: 0.2, w: 0.5, h: 0.45 },
    defaultColor: '#ffffff',
    popularity: 98,
    tags: ['stationery', 'notebook', 'leather', 'journal'],
    previewAsset: 'Photo from GFXTAB(1).jpg',
  },
  {
    id: 'tshirt-oversized',
    name: 'Architectural Column Banner Mockup',
    category: 'print',
    icon: '🏛️',
    description: 'Corporate outdoor banner template styled next to clean minimalist columns',
    printZone: { x: 0.2, y: 0.18, w: 0.6, h: 0.5 },
    defaultColor: '#1a1a1a',
    popularity: 92,
    tags: ['outdoor', 'banner', 'architectural', 'print'],
    previewAsset: 'Photo from GFXTAB(2).jpg',
  },
  {
    id: 'book-cover',
    name: 'Book Cover',
    category: 'print',
    icon: '📚',
    description: 'Hardcover book, full-cover artwork',
    printZone: { x: 0.05, y: 0.02, w: 0.9, h: 0.96 },
    defaultColor: '#2c2c2c',
    popularity: 87,
    tags: ['print', 'publishing', 'book'],
    previewAsset: 'Artboard 1 copy.jpg',
  },
  {
    id: 'mug-ceramic',
    name: 'Ceramic Mug',
    category: 'merchandise',
    icon: '☕',
    description: '11oz white ceramic mug, wraparound print',
    printZone: { x: 0.15, y: 0.2, w: 0.7, h: 0.55 },
    defaultColor: '#ffffff',
    popularity: 85,
    tags: ['merch', 'drinkware', 'mug'],
    previewAsset: 'Photo from GFXTAB(11).jpg',
  },
  {
    id: 'poster-a3',
    name: 'A3 Poster',
    category: 'print',
    icon: '🗒️',
    description: 'A3 portrait poster, full-bleed print',
    printZone: { x: 0.04, y: 0.04, w: 0.92, h: 0.92 },
    defaultColor: '#ffffff',
    popularity: 90,
    tags: ['print', 'poster', 'wall art'],
    previewAsset: 'A4-Flyer-Mock-Up 1.jpg',
  },
  {
    id: 'business-card',
    name: 'Business Card',
    category: 'print',
    icon: '🪪',
    description: 'Standard 3.5×2in card, double-sided',
    printZone: { x: 0.08, y: 0.1, w: 0.84, h: 0.8 },
    defaultColor: '#0d0d1a',
    popularity: 82,
    tags: ['print', 'branding', 'card'],
    previewAsset: 'Photo from GFXTAB(17).jpg',
  },
  {
    id: 'hoodie',
    name: 'Pullover Hoodie',
    category: 'apparel',
    icon: '🧥',
    description: 'Premium fleece hoodie, chest + back',
    printZone: { x: 0.28, y: 0.18, w: 0.44, h: 0.38 },
    defaultColor: '#222222',
    popularity: 88,
    tags: ['apparel', 'hoodie', 'streetwear'],
    previewAsset: 'Photo from GFXTAB(3).jpg',
  },
  {
    id: 'tote-bag',
    name: 'Canvas Tote Bag',
    category: 'accessories',
    icon: '👜',
    description: 'Natural canvas tote, front panel',
    printZone: { x: 0.2, y: 0.15, w: 0.6, h: 0.6 },
    defaultColor: '#d4c5a0',
    popularity: 78,
    tags: ['accessories', 'bag', 'eco'],
    previewAsset: 'Photo from GFXTAB(4).jpg',
  },
  {
    id: 'cap-5panel',
    name: '5-Panel Cap',
    category: 'accessories',
    icon: '🧢',
    description: 'Flat brim 5-panel, front panel embroidery zone',
    printZone: { x: 0.3, y: 0.15, w: 0.4, h: 0.5 },
    defaultColor: '#1a1a1a',
    popularity: 75,
    tags: ['accessories', 'cap', 'headwear'],
    previewAsset: 'Photo from GFXTAB(5).jpg',
  },
  {
    id: 'phone-case',
    name: 'Phone Case',
    category: 'accessories',
    icon: '📱',
    description: 'Slim matte case, full back panel',
    printZone: { x: 0.05, y: 0.08, w: 0.9, h: 0.84 },
    defaultColor: '#111111',
    popularity: 72,
    tags: ['accessories', 'phone', 'tech'],
    previewAsset: 'Photo from GFXTAB(6).jpg',
  },
  {
    id: 'sticker-sheet',
    name: 'Sticker Sheet',
    category: 'print',
    icon: '✨',
    description: 'A5 die-cut sticker sheet',
    printZone: { x: 0.05, y: 0.05, w: 0.9, h: 0.9 },
    defaultColor: '#ffffff',
    popularity: 70,
    tags: ['print', 'stickers', 'fun'],
    previewAsset: 'Photo from GFXTAB(7).jpg',
  },
  {
    id: 'flyer-a4',
    name: 'A4 Flyer',
    category: 'print',
    icon: '📄',
    description: 'A4 portrait marketing flyer',
    printZone: { x: 0.04, y: 0.04, w: 0.92, h: 0.92 },
    defaultColor: '#ffffff',
    popularity: 83,
    tags: ['print', 'flyer', 'marketing'],
    previewAsset: 'A4-Flyer-Mock-Up 2.jpg',
  },
  {
    id: 'packaging-box',
    name: 'Product Box',
    category: 'packaging',
    icon: '📦',
    description: 'Retail packaging box, front face',
    printZone: { x: 0.08, y: 0.05, w: 0.84, h: 0.9 },
    defaultColor: '#ffffff',
    popularity: 80,
    tags: ['packaging', 'box', 'retail'],
    previewAsset: 'Kiddicare Nappy Pant mockup.png',
  },
  {
    id: 'notebook',
    name: 'Hardcover Notebook',
    category: 'stationery',
    icon: '📓',
    description: 'A5 hardcover notebook, cover design',
    printZone: { x: 0.08, y: 0.06, w: 0.84, h: 0.88 },
    defaultColor: '#1a1a2e',
    popularity: 68,
    tags: ['stationery', 'notebook', 'gifts'],
    previewAsset: 'Artboard 1 copy 2.jpg',
  },
  {
    id: 'water-bottle',
    name: 'Water Bottle',
    category: 'merchandise',
    icon: '🫙',
    description: '500ml insulated bottle, wraparound',
    printZone: { x: 0.18, y: 0.15, w: 0.64, h: 0.65 },
    defaultColor: '#e0e0e0',
    popularity: 73,
    tags: ['merch', 'drinkware', 'outdoor'],
    previewAsset: 'Photo from GFXTAB(8).jpg',
  },
  {
    id: 'canvas-bag',
    name: 'Backpack',
    category: 'accessories',
    icon: '🎒',
    description: 'School/travel backpack front panel',
    printZone: { x: 0.22, y: 0.18, w: 0.56, h: 0.55 },
    defaultColor: '#2a2a2a',
    popularity: 65,
    tags: ['accessories', 'backpack', 'bag'],
    previewAsset: 'Photo from GFXTAB(9).jpg',
  },
  {
    id: 'mousepad',
    name: 'Desk Mat',
    category: 'stationery',
    icon: '🖱️',
    description: 'Extra large desk mat, full surface',
    printZone: { x: 0.02, y: 0.02, w: 0.96, h: 0.96 },
    defaultColor: '#1a1a1a',
    popularity: 60,
    tags: ['stationery', 'desk', 'gaming'],
    previewAsset: 'Photo from GFXTAB(10).jpg',
  },
  {
    id: 'pillow',
    name: 'Throw Pillow',
    category: 'merchandise',
    icon: '🛋️',
    description: '45×45cm cushion cover, front face',
    printZone: { x: 0.05, y: 0.05, w: 0.9, h: 0.9 },
    defaultColor: '#f0f0f0',
    popularity: 55,
    tags: ['merch', 'home', 'pillow'],
    previewAsset: 'Photo from GFXTAB(12).jpg',
  },
  {
    id: 'banner-roll',
    name: 'Roll-Up Banner',
    category: 'print',
    icon: '🚩',
    description: '85×200cm retractable banner',
    printZone: { x: 0.04, y: 0.02, w: 0.92, h: 0.96 },
    defaultColor: '#ffffff',
    popularity: 58,
    tags: ['print', 'banner', 'events'],
    previewAsset: 'A4-Flyer-Mock-Up 3.jpg',
  },
  {
    id: 'frame-print',
    name: 'Framed Print',
    category: 'merchandise',
    icon: '🖼️',
    description: '30×40cm framed wall art print',
    printZone: { x: 0.06, y: 0.06, w: 0.88, h: 0.88 },
    defaultColor: '#ffffff',
    popularity: 77,
    tags: ['merch', 'wall art', 'frame'],
    previewAsset: 'A4-Flyer-Mock-Up 4.jpg',
  },
];

// Products that appear in the 3D orbit (top 5 by popularity)
export const ORBIT_PRODUCTS = PRODUCTS.filter(p =>
  ['tshirt-crew', 'book-cover', 'mug-ceramic', 'poster-a3', 'business-card'].includes(p.id)
);

export default PRODUCTS;
